wee: build from source for linux and windows

diff --git a/wee/Makefile b/wee/Makefile
--- a/wee/Makefile
+++ b/wee/Makefile
@@ -1,9 +1,5 @@
 GRUBUTILS_DIR=grubutils
-GRUBUTILS_REV=115
-GRUBUTILS_SVN=http://$(GRUBUTILS_DIR).googlecode.com/svn/$(GRUBUTILS_DIR)
-
-WEESETUP_URL:=https://grubutils.googlecode.com/files
-WEESETUP_PACKAGE:=weesetup-2013-09-25.zip
+GRUBUTILS_GIT=https://github.com/cmtsij/$(GRUBUTILS_DIR)
 
 all:
 	@echo "Usage:"
@@ -12,34 +8,50 @@ all:
 	@echo "make distclean           # clean downlaod, build and installed wee"
 
 install: install_linux install_windows
-	make clean
 
-$(GRUBUTILS_DIR)_build:
-	# clean last one
-	rm -rf $(GRUBUTILS_DIR)
+.PHONY: $(GRUBUTILS_DIR)
+
+clone:
 	# download
-	git svn clone -r $(GRUBUTILS_REV) --preserve-empty-dirs "$(GRUBUTILS_SVN)"
+	if [ ! -f $(GRUBUTILS_DIR)/.git/.cloned ]; then\
+	fi
+
+$(GRUBUTILS_DIR)/.git/.cloned:
+	rm -rf $(GRUBUTILS_DIR)
+	git clone $(GRUBUTILS_GIT)
+	touch $(GRUBUTILS_DIR)/.git/.cloned
+
+
+build_linux: $(GRUBUTILS_DIR)/.git/.cloned
 	# patch
-	for file in patches/*; do cat $$file | (cd $(GRUBUTILS_DIR) && git am -k); done
-	mv $(GRUBUTILS_DIR) $@
+	# for file in patches/*; do cat $$file | (cd $(GRUBUTILS_DIR) && git am -k); done
+	#make -C  $(GRUBUTILS_DIR)
+	make -C $(GRUBUTILS_DIR)/grubutils/wee
+	make -C $(GRUBUTILS_DIR)/grubutils/weesetup clean
+	make -C $(GRUBUTILS_DIR)/grubutils/weesetup
+	make -C $(GRUBUTILS_DIR)/grubutils/grubinst
 
-install_linux: $(GRUBUTILS_DIR)_build
-	make -C $</wee
-	make -C $</weesetup
-	# install
-	mkdir -p doc
-	cp $</wee/{README.txt,ChangeLog.txt} doc/
+build_windows: $(GRUBUTILS_DIR)/.git/.cloned
+	@x86_64-w64-mingw32-gcc -v >/dev/null 2>&1 || (printf "Error: Please install missing package:\n\tapt-get install mingw-w64\n" && exit 1)
+	make -C $(GRUBUTILS_DIR)/grubutils/wee
+	make -C $(GRUBUTILS_DIR)/grubutils/weesetup clean
+	make -C $(GRUBUTILS_DIR)/grubutils/weesetup OSTYPE=MINGW CC=x86_64-w64-mingw32-gcc
+
+install_linux: build_linux
 	mkdir -p bin
-	cp $</wee/wee{63,127}.mbr bin/
-	cp $</weesetup/bin/weesetup bin/
+	cp $(GRUBUTILS_DIR)/grubutils/wee/wee{63,127}.mbr bin/
+	cp $(GRUBUTILS_DIR)/grubutils/weesetup/weesetup bin/
+	cp $(GRUBUTILS_DIR)/grubutils/grubinst/grubinst bin/
+	cp $(GRUBUTILS_DIR)/grubutils/grubinst/grubmenu bin/
 
-install_windows:
-	wget -q -N $(WEESETUP_URL)/$(WEESETUP_PACKAGE) -O $(WEESETUP_PACKAGE)
-	unzip -o -d bin $(WEESETUP_PACKAGE)
+
+install_windows: build_windows
+	mkdir -p bin
+	cp $(GRUBUTILS_DIR)/grubutils/weesetup/weesetup.exe bin/
 
 clean:
-	# clean source
-	rm -rf $(WEESETUP_PACKAGE) $(GRUBUTILS_DIR) $(GRUBUTILS_DIR)_build
+	#-cd $(GRUBUTILS_DIR) && git clean -xfd
+	rm -rf $(GRUBUTILS_DIR)
 
 distclean: clean
 	# clean installed
